### ISSUE TITLE
Having no write function requires the use of a very confusing syntax

### ISSUE THREAD

**Issue by Ragarnoy** [Hirtol/egui_memory_editor#4]
You cannot just use `None` when wanting to only use a read function, I don't know if there's any simpler way  of doing what I did which was `None as Option<fn(&mut T, Address, u8) -> ()>,`

**Comment by Hirtol** [comment]
The easier way of writing it would be `None::<fn(&mut T, Address, u8)>`.

I do agree that it's not a particularly intuitive or pretty API, hence why the `window_ui_read_only` and `window_ui` calls are separate. I assume you're using `draw_editor_contents` directly? I'll add a read only variant for that one as well.

Ideally there'd be a way to just pass `None`, but I haven't managed to find one.

**Comment by Ragarnoy** [comment]
Thanks, it's weird that there isn't a simpler way of doing what you're trying to do
