### ISSUE TITLE
Add a function to modify the range after the editor has been created

### ISSUE THREAD

**Issue by Kryptos-FR** [Hirtol/egui_memory_editor#5]
I find myself in a situation where I should reuse a memory editor for data that can change (and also the range).

For the moment, I have to recreate the whole editor each time, since `MemoryEditor::with_address_range()` uses the builder pattern.
```rust
let mem: &mut [u8] = ...;
let mut mem_editor = MemoryEditor::new().with_address_range("All", 0..mem.len());
mem_editor.draw_editor_contents_read_only(ui, mem, |mem, address| mem[address].into());
```

This also forces me to clone the `MemoryEditorOptions` if I want it to persist that and give it to the next instance of `MemoryEditor`:
```rust
let mut mem_editor = ...;
if let Some(options) = &self.editor_options {
  mem_editor = mem_editor.with_options(options.clone());
}
mem_editor.draw_editor_contents_read_only(...);
self.editor_options = Some(mem_editor.options.clone());
```

And because a new instance of `MemoryEditor` is created each time, some functionalities (such as goto) don't work properly.

Ideally I would like to create a single instance of `MemoryEditor` and keep it as a field of a struct (similarly to what is done in the `examples/simple` on this repo, and still be able to modify the range whenever needed:
```rust
struct MyStruct {
  Option<MemoryEditor> editor,
}

impl MyStruct {
  pub fn on_frame_update(ui: &mut Ui) {
    let mem_editor = self.editor.get_or_insert_with(|| {
      MemoryEditor::new()
    });
    // ...
    let mem: &mut [u8] = ...;
    mem.set_address_range("All", 0..mem.len());
    mem_editor.draw_editor_contents_read_only(ui, mem, |mem, address| mem[address].into());
  }
}
```

Therefore, I would suggest to add a function such as:
```rust
impl MemoryEditor {
  pub fn set_address_range(&mut self, range_name: impl Into<String>, address_range: Range<Address>) {
    // ...
  }
}
```

Likely the same could be applied to `MemoryEditorOptions`:
```rust
impl MemoryEditor {
  pub fn set_options(&mut self, options: MemoryEditorOptions) {
    self.options = options
  }
}
```

And to avoid code duplication, the builder functions could be rewritten as:
```rust
#[must_use]
pub fn with_address_range(mut self, range_name: impl Into<String>, address_range: Range<Address>) -> Self {
  self.set_address_range(range_name, address_range);
  self
}

pub fn set_address_range(&mut self, range_name: impl Into<String>, address_range: Range<Address>) {
  self.address_ranges.insert(range_name.into(), address_range);
  self.frame_data.memory_range_combo_box_enabled = self.address_ranges.len() > 1;
  if let Some((name, _)) = self.address_ranges.iter().next() {
      self.options.selected_address_range = name.clone();
  }
}

#[must_use]
pub fn with_options(mut self, options: MemoryEditorOptions) -> Self {
  self.set_options(options);
  self
}

pub fn set_options(&mut self, options: MemoryEditorOptions) {
  self.options = options;
}
```

If that's ok, I can create a PR with the above changes.

**Comment by Hirtol** [comment]
I agree that it'd probably be useful to be able to modify the available ranges whilst maintaining the same editor instance. 

Your proposal can work for now, but ideally there would be a way to delete an existing range as well while maintaining the invariant that there needs to be *at least* one range (or just accept a run-time panic...). That's probably something for the future, however. 

Feel free to submit the PR with your suggestions!
