### ISSUE TITLE
License is not included in the repository

### ISSUE THREAD

**Issue by IvarWithoutBones** [Hirtol/egui_memory_editor#7]
Hi, thanks for your work on this crate! It will save me a ton of time and effort compared to a home-made solution.

I just have one question regarding the projects license. I noticed that this repository does not ship any, even though the crates.io page notes that it is licensed under either Apache 2 or MIT. I was wondering if that licensing choice was intentional?

I am not a legal expert, but I believe both of those licenses require that a copy is bundled when distributing the source code. Because of this I suggest it would be best if you could include them in the Github repository as well.

Once again thanks for this crate, I'm really looking forward to integrating it with a project of mine :)

**Comment by Hirtol** [comment]
Thanks for pointing that out, I indeed forgot to add the license files to this repository!
